### ISSUE TITLE
Register controller

### ISSUE THREAD

**Issue by 8cells** [vsternbach/angular-ts-decorators#24]
How can I register controller with NgModule decorator?

`.controller('myController', myController)`

**Comment by vsternbach** [comment]
I guess you mean controller? There should not be any standalone controllers, you should turn it into component

**Comment by 8cells** [comment]
Sometimes I needs to register a controller (to be backward compatible).
My typescript code is mixed with old javascript code.

So there is no such option and I have to register modules in the old way? What a pity!

**Comment by vsternbach** [comment]
You can, but using old syntax, cause there's no controller decorator in angular 2, I'll post here an example a bit later

**Comment by vsternbach** [comment]
One solution I would suggest is to register you controller on different module (the one not decorated with @NgModule) and use it as dependency in your @NgModule:
```
// registering regular angularjs style
angular.module('legacyModule', []).controller('myController', myController);

@NgModule({
  name: 'NewModule',
  imports: [
    'legacyModule'
  ],
  declarations: [...]
})
export class NewModule {}
```
If it doesn't make sense in terms of functionality and this controller should be part of a new style @NgModule, then you can register you controller this way:
```
@NgModule({
  name: 'NewModule',
  declarations: [...]
})
export class NewModule {}

(NewModule as NgModule).module
.controller('myController', myController);
```

**Comment by eric-simonton-sama** [comment]
I'm just starting to use this tool today, but if I understand things correctly you can also do it like this:
```ts
@MyModule({
  id: 'myModuleName',
  ...
})
export class NewModule {}

angular.module('myModuleName').controller('myController', myController);
```

It was important for me to have that string to work with rather than imports, because I'm starting to port an angular app from Coffeescript via a Rails asset pipeline to Typescript via Webpack, and this lets me do 1 file at a time. I migrate the module to Webpack/Typescript using `id: 'oldNameHere'`, and all the components/services/etc defined it Coffeescript/Rails files continue to work!

**Comment by vsternbach** [comment]
Yep, that's all possible
