### ISSUE TITLE
ngModelController not mapping while using @Directive decorator

### ISSUE THREAD

**Issue by LalitAgrawala004** [vsternbach/angular-ts-decorators#38]
Hi 
I have directive used in html like attribute along with ng-model..
```
<div test-directive 
   ng-model="selectedOptions" name="testModel">
</div>
```

I am trying convert the directive using @Directive decorator like below 

```
@Directive({
	selector: '[test-directive]',
	transclude: true,
	require: {
		ngModel: '?ngModel'
	},
	templateUrl: 'template\test.html'
})
export class TestDirective implements AfterViewInit {
	private ngModel: INgModelController;
	
	constructor() {
	}
	
	public ngAfterViewInit(): void {
		//use ngModel here..
		this.ngModel.$render  
	}
}
```
here, ngModel is not getting mapped to ngModelController.. I tried changing the directive to Component ( changed the html too..) real quick and found ngModel is getting mapped correctly but I need it work with @Directive.. any help would be highly appreciated..

**Comment by christophercr** [comment]
Hi, the problem here is that the ngAfterViewInit (which is at the end the Angular1 $postLink) is not the same as the directive's link function where ngModel is injected by Angular.

So, what you need to do is this:

1.- Add the "bindToController: true" option to your directive metadata so the ngModel gets mapped "magically" to the component controller. I know this property is discouraged and removed in Angular2 but we should keep in mind that we are just decorating an Angular1 directive which obviously has some differences in terms of implementation.
2.- Although your directive will work if you use ngAfterViewInit, be aware that in Angular2 the ngAfterViewInit is only available in Components and not in directives (see https://angular.io/guide/lifecycle-hooks) so you should use ngOnInit instead.

**Comment by vsternbach** [comment]
You can do this using ViewParent decorator, take a look at this pr https://github.com/vsternbach/angular-ts-decorators/pull/76
