### ISSUE TITLE
Dependency injection issue with Directives

### ISSUE THREAD

**Issue by vadim82** [vsternbach/angular-ts-decorators#4]
Looks like I am having a similar issue to (https://github.com/vsternbach/angular-ts-decorators/issues/3) with DI when using @Directive annotation and injecting things into the constructor. The first constructor argument is an array of everything.

```typescript
@Directive({
    selector: "nlImageDrop",
    scope: {    }
})
export class ImageDropDirective {

    static $inject = ["$log", "$parse"];
    constructor(
        private $log: ng.ILogService,
        private $parse: ng.IParseService
    ) { }

```

When this code runs, `$log` is an array and `$parse` is undefined. I think its a similar issue that was happening with @Pipe annotation before.

**Comment by vsternbach** [comment]
Yep, seems like the same type of problem, will look into that

**Comment by vsternbach** [comment]
Hey Vadim, besides the injection issue, I've revisited the whole directive concept compared to angular2+ and realized that in most cases there's no need to use compile or link function, but just a controller class can be used instead (all of the link function arguments can be injected manually into controller's constructor and all of the IController lifecycle hooks can be used).
The way it's implemented right now if compile or link methods defined on the directive class they will be used, otherwise directive's class will serve as directive's controller, of course both has access to arguments injected into constructor.

**Comment by vadim82** [comment]
That makes sense. My team is really liking using these decorators as it makes it easy to switch between angular 1 and angular 2 apps. 

Once you are done, could you please add some examples on directive usage?
