### ISSUE TITLE
Multiple of the same directive on a single page use the same context

### ISSUE THREAD

**Issue by Swiftwork** [vsternbach/angular-ts-decorators#49]
Hello,

I'm coming from Angular5 and absolutely love your work here. One of our clients is required to use AngularJS so this is a real lifesaver together with typescript. I have been trying to solve an issue where I dynamically add an `<a>` link using a directive to toggle the contents of said element. I wasn't able to do this DOM manipulation inside the standard directive controller without causing nested components to duplicate. I tried instead to use the legacy compile function which solved the duplication issue. However there seems to be an issue that I cannot solve where each directive's context seems linked. Every toggle causes the last to change. Is this due to `this` losing context?

```typescript
import { element as ngElement } from 'angular';
import { Directive, Input } from 'angular-ts-decorators';

@Directive({
  selector: 'dExpandable',
})
export class ExpandableDirective {

  private element: ng.IAugmentedJQuery;
  private toggler: ng.IAugmentedJQuery;
  private expanded = false;

  constructor(
    // Cannot inject when using legacy compile function
  ) {
    this.onToggle = this.onToggle.bind(this);
  }

  compile(element: ng.IAugmentedJQuery, attrs: ng.IAttributes) {
    this.element = element;
    this.element.attr('aria-expanded', this.expanded.toString());
    this.toggler = ngElement('<a class="d-expandable--toggler"></a>');
    this.toggler.on('click', this.onToggle);
    this.element.prepend(this.toggler);
  }

  onToggle() {
    this.expanded = !this.expanded;
    this.element.attr('aria-expanded', this.expanded.toString());
  }
}
```

This might be unrelated to your decorators, but any pointers would be greatly appreciated!

Kind Regards
Erik Hughes

**Comment by Swiftwork** [comment]
I think I figured out the issue but not the solution. Currently above assumes that the directive class should retain its context because the default behaviour for classes is to call `new ClassConstructor()` however the decorator instead copies the `compile` and `link` functions into a new options object. This object isn't unique and therefore `this` isn't either. All bindings are replaced by the last instance. I guess I am looking for something along the lines of:

https://github.com/toddmotto/angularjs-styleguide#directives

How do I/we solve this? Can we use a factory function for legacy directives? :)

**Comment by vsternbach** [comment]
Hi Erik
It's clearly a bug in the implementation of Directive decorator, indeed as you've said link and compile (and of course all other properties and methods) would be binded to the only one instance of Directive class, so all instances of this directive will share the same state.
Right now I don't see any feasible solution to this problem, i.e. I don't see how it's possible to support $compile and $link being methods of Directive's class, so I'm thinking of removing support for this at all, so any legacy code for directives using link or compile should stay in a legacy syntax without decorators and also should be registered in a legacy way, since this legacy code couldn't be migrated to angular 5 without refactoring anyway.
Regarding your PR on Pipes, didn't know about the hidden $stateful property, but even with this change it still won't work as expected, since this stateful filter will share the state with all other instances of the same filter, it's implemented in the same way as directive's link and compile, so maybe I should update the documentation saying that Pipe decorator can only be used when migrating stateless filters and stateful filters should be registered using the legacy syntax.
Any thoughts?

**Comment by Swiftwork** [comment]
Hmm I see what you mean, unfortunately I kinda agree ^^. Just loved the decorators so much. But before I make any decisions I will think it over and see what is feasible. :)

**Comment by Swiftwork** [comment]
@vsternbach Thank you for taking your time to look into the issue. I have had quite a lot going on, but I believe I have reached the same verdict as you. Keep the decorators simple and as compatible with Angular as you can. I would even go as far as to remove most of the legacy support and extend the documentation regarding this change. Short example how to create a legacy registration of filters and directives instead and maybe refer to a guide on the topic.
