### ISSUE TITLE
Implement @Inject

### ISSUE THREAD

**Issue by mebibou** [vsternbach/angular-ts-decorators#57]
Would it be possible to use `@Inject()` to inject a value that has a name not matching the variable name? i.e. if I have a provider like this:
```
@Injectable('My.Service')
export class MyService {}
```
And later I want to inject it, I will have to use the `$inject`. I think it would be very neat to do this instead:
```
export class MyController {
  constructor(@Inject('My.Service') service: MyService) {}
}
```
I don't know if this is possible though

**Comment by vsternbach** [comment]
For now it's not supported, but I'll look into adding this feature

**Comment by mebibou** [comment]
Thanks for adding this so quickly, I added it in my app and it works well when I bundle everything with webpack, however when using Karma and `karma-typescript` all the `@Inject` throw the error 

> Annotations should be provided as static $inject property in order to use @Inject decorator

Do you have any idea why?

**Comment by vsternbach** [comment]
I suppose you have ngAnnotate preprocessor in your webpack build, but not in karma, you probably need to add [karma-ng-annotate-preprocessor](https://github.com/evangalen/karma-ng-annotate-preprocessor), although I didn't try it.
The problem is that I removed annotations from the library, because it can work only on unuglified code, but when mangling is enabled in uglify, it changes parameter names, so they can not be annotated at runtime and in Inject decorator I am assuming that the code is explicitly annotated using ngAnnotate or using static $inject property

**Comment by mebibou** [comment]
@vsternbach yes you are right, adding `ng-annotate` after `karma-typscript` worked like a charm, thanks
