### ISSUE TITLE
Use with "downgradeComponent()"?

### ISSUE THREAD

**Issue by oBusk** [vsternbach/angular-ts-decorators#69]
Would it be possible to use `@NgModule` with one or several directives which are downgraded components using `{ downgradeComponent } from '@angular/upgrade/static';`?

I tried 

```typescript
import { downgradeComponent } from '@angular/upgrade/static';
import { Directive, NgModule } from 'angular-ts-decorators';

import { CoolComponent } from '../app/cool.component';

@Directive(downgradeComponent({ component: CoolComponent })
class Downgraded { }

@NgModule({
  id: 'AppModule',
  declarations: [
    Downgraded,
  ],
})
export class AppModule { }
```

Otherwise, would it be sensible to have another function to get the correct meta data from a downgraded component?

**Comment by mebibou** [comment]
@oBusk I don't think the purpose of the library here is to work on a angular + AngularJS application, so adding something specifically to help do that does not make sense, especially something that has no meaning either in angular or in AngularJS. But maybe you could create your own plugin to do this? otherwise for your case, I would do it like this:
```
import { Component } from '@angular/core';
import { downgradeComponent } from '@angular/upgrade/static';
import { NgModule } from 'angular-ts-decorators';

@Component({
  selector: 'cool'
})
export class CoolComponent {}

@NgModule({
  id: 'AppModule'
})
export class AppModule { }

(AppModule as NgModule).module.directive('cool', downgradeComponent({ component: CoolComponent });
```
